location             = "East US"
resource_group_name  = "my-resource-group"
vnet_name            = "my-vnet"
vnet_address_space   = ["10.0.0.0/16"]
subnet_name          = "my-subnet"
subnet_address_prefixes = ["10.0.1.0/24"]
storage_account_name = "skillupbucket"
aks_name             = "my-aks-cluster"
dns_prefix           = "myaksdns"
api_server_authorized_ip_ranges = []
